### ISSUE TITLE
feat: set width and height

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/freeze#14]
it would be great to be able to set the width and make the content wrap. That would make the images look more consistent. If the content exceeds the height, it can be clipped

**Comment by ethanholz** [comment]
Has this been implemented yet? From my recent testing at launch it seems that longer lines are still truncated rather than wrapped. This occurs when just running `freeze <filename>`. Is this something that would require setting the width of the terminal window?
![freeze](https://github.com/charmbracelet/freeze/assets/6245717/5ed6fcc7-4170-4a14-9984-2822ac130699)

**Comment by andyfoster** [comment]
Doesn't look to be fixed for me. Just crops the code at the specified width.

**Comment by maaslalani** [comment]
Hey! Thank you for the comments, we will soon add text wrapping on freeze screenshots!

**Comment by maaslalani** [comment]
Thanks for the comments, again. This is now fixed:

* https://github.com/charmbracelet/freeze/pull/98
