### ISSUE TITLE
"Dynamic output" generates a giant image

### ISSUE THREAD

**Issue by Su3h7aM** [charmbracelet/freeze#61]
**Describe the bug**
Commands that have a "dynamic output" generate a giant image containing all the "frames".

**To Reproduce**
In my case, I tried to generate an image with [hyperfine](https://github.com/sharkdp/hyperfine), but the output was an image measuring 240273 x 668px.

**Expected behavior**
Generate an image with the last command output.

**Screenshots**
I'm not going to attach the generating image because it's too big, and it's impossible to see anything without a lot of zoom.

**Desktop**
 - OS: Fedora 40 (kernel 6.8.2)
 - DE: KDE Plasma 6

**Comment by Su3h7aM** [comment]
It also happens that system monitors like [htop](https://github.com/htop-dev/htop), [glances](https://github.com/nicolargo/glances), [btop](https://github.com/aristocratos/btop) generate unusable images.

btop output:
![btop](https://github.com/charmbracelet/freeze/assets/19878770/95cd774e-6aa4-4b88-a9a7-d94ad6f0c9d7)
glances output:
![glances](https://github.com/charmbracelet/freeze/assets/19878770/7f7cad36-c181-4cab-8353-a5eb97f56c62)
htop output:
```
ERROR  Bad SVG
XML syntax error on line 13: illegal character code U+0008
```

I was unsure whether to create a new issue or add it here. If you prefer, I can create another issue, so that it is more organized.

**Comment by maaslalani** [comment]
For `btop`, the output can likely be fixed by allowing people to resize the terminal by exposing `--row`/`--col` attributes and setting them dynamically here:

https://github.com/charmbracelet/freeze/blob/main/pty.go#L23-L24

**Comment by maaslalani** [comment]
I see that `hyperfine` is a TUI which can output lots of output while it is benchmarking the tool. This is likely all getting captured within the input (We can fix / limit that on our end).

However, for `hyperfine` I would highly recommend using `tmux capture-pane` with the result so that you can capture the final output. See the [Screenshot TUIs](https://github.com/charmbracelet/freeze?tab=readme-ov-file#screenshot-tuis) section in the README: https://github.com/charmbracelet/freeze?tab=readme-ov-file#screenshot-tuis

We will make this better in the future to solve for these use cases as well!

**Comment by Su3h7aM** [comment]
> For `btop`, the output can likely be fixed by allowing people to resize the terminal by exposing `--row`/`--col` attributes and setting them dynamically here:
> 
> https://github.com/charmbracelet/freeze/blob/main/pty.go#L23-L24

Cool, that would be a great addition. It may end up being useful on other occasions.

**Comment by maaslalani** [comment]
@Su3h7aM You may also want to check out https://github.com/charmbracelet/vhs for recording TUIs which will provide the full animation of Hyperfine as well (and it can also produce screenshots).
